/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { APIPurchaseDetailReportLine } from './aPIPurchaseDetailReportLine';


export interface APIPurchaseDetailReport { 
    apiType?: string;
    productUser?: string;
    dateFrom?: Date;
    dateTo?: Date;
    apiPurchaseDetailline?: Array<APIPurchaseDetailReportLine>;
}
