/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MultipleBankEntryData } from './multipleBankEntryData';
import { TransactionInfo } from './transactionInfo';


export interface BankReconciliationReportLine { 
    id?: number;
    txInfo?: TransactionInfo;
    description?: string;
    debit?: number;
    credit?: number;
    cheque?: string;
    chequeDate?: Date;
    bankDate?: Date;
    balance?: number;
    bankStmtList?: Array<MultipleBankEntryData>;
    transaction?: TransactionInfo;
}
