/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DatabaseCreateInput { 
    dbName?: string;
    imageLocation?: string;
    product?: string;
    dbType?: DatabaseCreateInput.DbTypeEnum;
    host?: string;
    port?: string;
    username?: string;
    password?: string;
    h2DbPath?: string;
    dbPathIsFolderGroup?: boolean;
}
export namespace DatabaseCreateInput {
    export type DbTypeEnum = 'POSTGRES' | 'H2';
    export const DbTypeEnum = {
        POSTGRES: 'POSTGRES' as DbTypeEnum,
        H2: 'H2' as DbTypeEnum
    };
}
