/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DayBookLineDetail } from './dayBookLineDetail';
import { TransactionInfo } from './transactionInfo';


export interface DayBookLine { 
    type?: string;
    voucherNumber?: string;
    description?: string;
    debit?: number;
    credit?: number;
    transactionDate?: Date;
    transaction?: TransactionInfo;
    ledgerString?: string;
    productUser?: string;
    transactionDateWithTime?: string;
    chequeNumber?: string;
    detailLines?: Array<DayBookLineDetail>;
}
