/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EInvoiceSellerDtls { 
    gstin?: string;
    lglNm?: string;
    trdNm?: string;
    addr1?: string;
    addr2?: string;
    loc?: string;
    pin?: number;
    stcd?: string;
    ph?: string;
    em?: string;
}
