/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GatePassDetailLine } from './gatePassDetailLine';
import { IGrainAgentItem } from './iGrainAgentItem';
import { ILedger } from './iLedger';


export interface GatePassDetail { 
    ledger?: ILedger;
    dateFrom?: Date;
    dateTo?: Date;
    item?: IGrainAgentItem;
    gatePassDetailLines?: Array<GatePassDetailLine>;
}
