/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GSTR2B2burReportLine } from './gSTR2B2burReportLine';


export interface GSTR2B2burReport { 
    gstr2B2burReportLines?: Array<GSTR2B2burReportLine>;
    purchaseTxCount?: number;
}
