/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GSTR2B2BMatchingReport } from './gSTR2B2BMatchingReport';


export interface Gstr2MatchingReport { 
    b2bMatchingreport?: GSTR2B2BMatchingReport;
}
