/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GSTR2B2bReportLine } from './gSTR2B2bReportLine';


export interface GSTRb2bMatchingReportLine { 
    line?: GSTR2B2bReportLine;
    importedLine?: GSTR2B2bReportLine;
    status?: number;
    itemsNotMatched?: Array<string>;
}
