/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GSTR1B2bReportLine } from './gSTR1B2bReportLine';


export interface GSTR1B2bReport { 
    b2bReportLines?: Array<GSTR1B2bReportLine>;
    saleTxCount?: number;
}
