/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GSTR2B2bReportLine } from './gSTR2B2bReportLine';


export interface GSTR2B2bReport { 
    gstr2B2bReportLines?: Array<GSTR2B2bReportLine>;
    purchaseTxCount?: number;
}
