/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GSTR1B2clReportLine { 
    invoiceNumber?: string;
    invoiceDate?: Date;
    invoiceValue?: number;
    placeOfSupply?: string;
    applicablePercentageOfTax?: string;
    rate?: number;
    taxableValue?: number;
    cessAmount?: number;
    eCommerceGstin?: string;
    saleFromBondedWh?: string;
}
