/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GSTR9TaxPaidReportLine { 
    description?: string;
    taxPayable?: number;
    paidThrTax?: number;
    cgst?: number;
    sgst?: number;
    igst?: number;
    cess?: number;
    sheetValidation?: string;
}
