/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GSTR9ITCAvailReportLine } from './gSTR9ITCAvailReportLine';


export interface GSTR9ITCAvail { 
    reportLines?: Array<GSTR9ITCAvailReportLine>;
    sixBMap?: { [key: string]: Array<GSTR9ITCAvailReportLine>; };
    sixCMap?: { [key: string]: Array<GSTR9ITCAvailReportLine>; };
    sixDMap?: { [key: string]: Array<GSTR9ITCAvailReportLine>; };
    sixEMap?: { [key: string]: Array<GSTR9ITCAvailReportLine>; };
}
