/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IGrainAgentItem } from './iGrainAgentItem';
import { ILedger } from './iLedger';


export interface HeapRegisterLine { 
    transactionDate?: Date;
    sellerLedger?: ILedger;
    buyerLedger?: ILedger;
    sellerAddress?: string;
    item?: IGrainAgentItem;
    aprxWt?: number;
    correctWt?: number;
    dateOfSale?: Date;
    dateOfWeight?: Date;
    totslUnits?: number;
    rate?: number;
    totalLabour?: number;
    getjFormNo?: string;
}
