/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ILedger } from './iLedger';


export interface HisabkhataArgument { 
    dateFrom?: Date;
    dateTo?: Date;
    ledger?: ILedger;
    interestFrom?: Date;
    interestTo?: Date;
    rate?: number;
    graceDays?: number;
    mandiExp?: number;
    shortage?: number;
    gaushala?: number;
    bonus?: number;
    otherExp?: number;
    commission?: number;
    bardana?: number;
    cloth?: number;
    discount?: number;
    dateAfterUseSplInterest?: number;
    splInterest?: number;
    withOpeningBalance?: boolean;
    isMonthWise?: boolean;
    noOfDaysForDayWiseInterestCalculation?: number;
}
