/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ICompany { 
    modules?: string;
    guid?: string;
    companyId?: string;
    email?: string;
    mobile?: string;
    singleLineAddressWithoutPin?: string;
    address2?: string;
    fax?: string;
    phone?: string;
    address1?: string;
    address3?: string;
    weblink?: string;
    pin?: string;
    licenceNo?: string;
    pan?: string;
    printname?: string;
    serviceTax?: string;
    booksFrom?: Date;
    gstin?: string;
    country?: string;
    contactperson?: string;
    licenceExpiryDate?: Date;
    singleLineAddressWithPin?: string;
    name?: string;
    state?: string;
    description?: string;
    id?: number;
    jacksontype?: string;
}
