/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ICity } from './iCity';
import { IFormReportLineDetail } from './iFormReportLineDetail';
import { IGrainAgentItem } from './iGrainAgentItem';
import { ILedger } from './iLedger';
import { IMandi } from './iMandi';
import { TransactionInfo } from './transactionInfo';


export interface IFormReportLine { 
    transaction?: TransactionInfo;
    transactionDate?: Date;
    mandi?: IMandi;
    partyLedger?: ILedger;
    city?: ICity;
    totalAmount?: number;
    item?: IGrainAgentItem;
    bag?: number;
    kgs?: number;
    rate?: number;
    qty?: number;
    expences?: number;
    bonus?: number;
    netAmount?: number;
    amount?: number;
    getiFormReportDetailLine?: Array<IFormReportLineDetail>;
    voucherNo?: string;
}
