/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IItemBatch { 
    alternateUnitWholeSalePrice?: number;
    expiryDate?: Date;
    itemName?: string;
    itemId?: number;
    rateCode?: string;
    mrp?: number;
    mfgDate?: Date;
    sellingPrice?: number;
    wholeSalePrice?: number;
    purchasePrice?: number;
    landingPrice?: number;
    alternateUnitMrp?: number;
    retailPrice?: number;
    alternateUnitRetailPrice?: number;
    alternateUnitLandingPrice?: number;
    alternateUnitSellingPrice?: number;
    alternateUnitPurchasePrice?: number;
    name?: string;
    description?: string;
    importedId?: number;
    logInfo?: string;
    productUserId?: number;
    creationdate?: Date;
    productUserName?: string;
    modificationdate?: Date;
    impCompanyGuid?: string;
    id?: number;
    jacksontype?: string;
}
