/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionInfo } from './transactionInfo';


export interface IJFormItemLine { 
    transaction?: TransactionInfo;
    rate?: number;
    itemName?: string;
    itemId?: number;
    packing?: number;
    dressing?: number;
    bonus?: number;
    aproxWt?: number;
    filtration?: number;
    quantity?: number;
    kgs?: number;
    bags?: number;
    bagId?: number;
    bagName?: string;
    expences?: number;
    totalAmount?: number;
    unloadingCost?: number;
    grossAmount?: number;
    iformlineseq?: number;
    noOfBagsWithBagName?: string;
    id?: number;
    jacksontype?: string;
}
