/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InnoventryFeatureInfo } from './innoventryFeatureInfo';


export interface InnoventryEditionFeatureInfo { 
    title?: string;
    license?: InnoventryEditionFeatureInfo.LicenseEnum;
    features?: Array<InnoventryFeatureInfo>;
    mrp?: number;
    rate?: number;
    upgradeRate?: number;
    productCode?: string;
}
export namespace InnoventryEditionFeatureInfo {
    export type LicenseEnum = 'NONE' | 'LITE' | 'BASIC' | 'PERSONAL' | 'STANDARD' | 'FULL';
    export const LicenseEnum = {
        NONE: 'NONE' as LicenseEnum,
        LITE: 'LITE' as LicenseEnum,
        BASIC: 'BASIC' as LicenseEnum,
        PERSONAL: 'PERSONAL' as LicenseEnum,
        STANDARD: 'STANDARD' as LicenseEnum,
        FULL: 'FULL' as LicenseEnum
    };
}
