/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface INotification { 
    shortDescription?: string;
    read?: boolean;
    url?: string;
    actionKey?: string;
    imageUrl?: string;
    validTill?: Date;
    notificationType?: number;
    notificationGroup?: string;
    userToNotify?: number;
    userToNotifyName?: string;
    title?: string;
    importedId?: number;
    logInfo?: string;
    productUserId?: number;
    creationdate?: Date;
    productUserName?: string;
    modificationdate?: Date;
    impCompanyGuid?: string;
    id?: number;
    jacksontype?: string;
}
