/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FTaxItem } from './fTaxItem';


export interface InvoiceFiscalizationResult { 
    requestedBy?: string;
    DT?: string;
    IC?: string;
    invoiceCounterExtension?: string;
    IN?: string;
    taxItems?: Array<FTaxItem>;
    verificationUrl?: string;
    verificationQRCode?: string;
    journal?: string;
    messages?: string;
    signedBy?: string;
    ID?: string;
    S?: string;
    totalCounter?: number;
    transactionTypeCounter?: number;
    totalAmount?: number;
    taxGroupRevision?: number;
    businessName?: string;
    TIN?: string;
    locationName?: string;
    address?: string;
    district?: string;
    hash?: string;
    MRC?: string;
}
