/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IProductUser { 
    password?: string;
    email?: string;
    mobile?: string;
    address2?: string;
    contactId?: number;
    fax?: string;
    phone?: string;
    address1?: string;
    address3?: string;
    middlename?: string;
    lastname?: string;
    firstname?: string;
    contactName?: string;
    readOnlyFlags?: number;
    userGroupName?: string;
    userReadOnly?: boolean;
    userGroupId?: number;
    permissionsEditable?: boolean;
    userGroupEditable?: boolean;
    displayName?: string;
    enabled?: boolean;
    name?: string;
    description?: string;
    importedId?: number;
    logInfo?: string;
    productUserId?: number;
    creationdate?: Date;
    productUserName?: string;
    modificationdate?: Date;
    impCompanyGuid?: string;
    id?: number;
    jacksontype?: string;
}
