/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ICostCenterLine } from './iCostCenterLine';
import { ITaxLine } from './iTaxLine';


export interface IServiceLine { 
    costCenterLines?: Array<ICostCenterLine>;
    internal?: boolean;
    rate?: number;
    quantity?: number;
    percentage?: boolean;
    taxGroup?: number;
    totalAmountBeforeBillDiscount?: number;
    taxableAmountBeforeBillDiscount?: number;
    taxAmount?: number;
    taxLines?: Array<ITaxLine>;
    totalAmount?: number;
    billDiscountFixed?: number;
    billDiscountPerc?: number;
    taxableAmount?: number;
    taxableEntityName?: string;
    totalTaxValue?: number;
    taxableEntityId?: number;
    taxGroupName?: string;
    internalRef?: string;
    description?: string;
    id?: number;
    jacksontype?: string;
}
