/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IStockLocation { 
    email?: string;
    mobile?: string;
    pincode?: string;
    address2?: string;
    fax?: string;
    cityId?: number;
    phone?: string;
    cityName?: string;
    address1?: string;
    address3?: string;
    storeName?: string;
    storeId?: number;
    typeName?: string;
    typeId?: number;
    contactPerson?: string;
    costCenterId?: number;
    costCenterName?: string;
    stockLocationtypeId?: number;
    stocklocationtypeName?: string;
    name?: string;
    description?: string;
    importedId?: number;
    logInfo?: string;
    productUserId?: number;
    creationdate?: Date;
    productUserName?: string;
    modificationdate?: Date;
    impCompanyGuid?: string;
    id?: number;
    jacksontype?: string;
}
