/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IStockAttributeGroupLine } from './iStockAttributeGroupLine';
import { TransactionInfo } from './transactionInfo';


export interface IStockDetailLine { 
    reason?: string;
    transaction?: TransactionInfo;
    amount?: number;
    rate?: number;
    itemName?: string;
    itemId?: number;
    unitName?: string;
    unitId?: number;
    taxAmount?: number;
    stockIn?: number;
    stockOut?: number;
    totalAmount?: number;
    stockLocationName?: string;
    alternateRateUsed?: boolean;
    stockLocationId?: number;
    netQuantity?: number;
    itemBatchId?: number;
    primaryStockRate?: number;
    primaryStockIn?: number;
    primaryStockOut?: number;
    itemBatchName?: string;
    attributeGroupLines?: Array<IStockAttributeGroupLine>;
    description?: string;
    id?: number;
    jacksontype?: string;
}
