/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ITaxClassLine { 
    taxClassId?: number;
    taxGroupId?: number;
    taxClassName?: string;
    billingGroupName?: string;
    taxGroupName?: string;
    billingClassificationId?: number;
    billingClassificationName?: string;
    billingGroupId?: number;
    id?: number;
    jacksontype?: string;
}
