/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemRegisterReportLine } from './itemRegisterReportLine';


export interface ItemRegisterReport { 
    itemName?: string;
    itemId?: number;
    toDate?: Date;
    fromDate?: Date;
    location?: string;
    openingStock?: number;
    closingStock?: number;
    closingStockValue?: number;
    showAlternateUnit?: boolean;
    unitName?: string;
    batch?: string;
    reportLines?: Array<ItemRegisterReportLine>;
}
