/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionInfo } from './transactionInfo';


export interface ITransactionAudit { 
    note?: string;
    tx?: TransactionInfo;
    status?: ITransactionAudit.StatusEnum;
    importedId?: number;
    logInfo?: string;
    productUserId?: number;
    creationdate?: Date;
    productUserName?: string;
    modificationdate?: Date;
    impCompanyGuid?: string;
    id?: number;
    jacksontype?: string;
}
export namespace ITransactionAudit {
    export type StatusEnum = 'COMPLETED' | 'HAS_ISSUES' | 'NO_STATUS';
    export const StatusEnum = {
        COMPLETED: 'COMPLETED' as StatusEnum,
        HASISSUES: 'HAS_ISSUES' as StatusEnum,
        NOSTATUS: 'NO_STATUS' as StatusEnum
    };
}
