/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IMandi } from './iMandi';
import { JFormReportLine } from './jFormReportLine';


export interface JFormDetail { 
    mandi?: IMandi;
    dateFrom?: Date;
    dateTo?: Date;
    totalBags?: number;
    totalKgs?: number;
    totalQty?: number;
    totalAmount?: number;
    totalExpenses?: number;
    totalNetAmount?: number;
    totalBillAmount?: number;
    totalBonus?: number;
    jformDetailReportLine?: Array<JFormReportLine>;
}
