/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LedgerSaleSummaryReportLine } from './ledgerSaleSummaryReportLine';


export interface LedgerSaleSummaryReport { 
    ledger?: string;
    ledgerId?: number;
    dateFrom?: Date;
    dateTo?: Date;
    reportLines?: Array<LedgerSaleSummaryReportLine>;
}
