/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IAttributeGroupLine } from './iAttributeGroupLine';
import { IContact } from './iContact';
import { IDocument } from './iDocument';
import { ILedger } from './iLedger';
import { ILedgerLabel } from './iLedgerLabel';
import { IOpeningBalanceTx } from './iOpeningBalanceTx';


export interface LedgerImpl extends ILedger { 
    bankLedger?: boolean;
    ledgerBalance?: number;
}
export namespace LedgerImpl {
}
