/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OrganizationStockSummaryItemReportLine { 
    companyName?: string;
    itemName?: string;
    itemId?: number;
    companyId?: number;
    numberOFDecimal?: number;
    quantity?: number;
    unitDisplayName?: string;
    unitId?: number;
    maxquantity?: number;
    minquantity?: number;
}
