/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductionItemSummaryGroupLine2 } from './productionItemSummaryGroupLine2';


export interface ProductionItemSummaryReport2 { 
    groupLines?: Array<ProductionItemSummaryGroupLine2>;
    totalQuantity?: number;
    totalAmount?: number;
    stockLocation?: string;
    item?: string;
    dateFrom?: Date;
    dateTo?: Date;
    itemGroup?: string;
}
