/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BalanceSheetReportLine } from './balanceSheetReportLine';
import { ProfitLossReportLine } from './profitLossReportLine';


export interface ProfitLossReport { 
    incomeReportLines?: Array<ProfitLossReportLine>;
    expensesReportLines?: Array<ProfitLossReportLine>;
    assetReportLines?: Array<BalanceSheetReportLine>;
    dateFrom?: Date;
    dateTo?: Date;
    balance?: number;
    showAccountWithZeroBalance?: boolean;
    currentPeriodProfit?: number;
}
