/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ILedger } from './iLedger';
import { SalesManReportDetailLine } from './salesManReportDetailLine';
import { TransactionInfo } from './transactionInfo';


export interface SalesManReportGroupLine { 
    txDate?: Date;
    nameOnBill?: string;
    transactionType?: string;
    salesManInfoReportLines?: Array<SalesManReportDetailLine>;
    totalBillAmount?: number;
    transaction?: TransactionInfo;
    voucherNo?: string;
    amount?: number;
    unit?: string;
    quantity?: number;
    rate?: number;
    ledger?: ILedger;
    itemName?: string;
}
