/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ITransactionStatus } from './iTransactionStatus';
import { StandardInventoryTxReportLine } from './standardInventoryTxReportLine';
import { TransactionInfo } from './transactionInfo';


export interface StandardInventoryTxReportGroupLine { 
    txDate?: Date;
    particulars?: string;
    billAmount?: number;
    transaction?: TransactionInfo;
    voucherNo?: string;
    usageReportGroupLines?: Array<StandardInventoryTxReportGroupLine>;
    transactionStatus?: ITransactionStatus;
    details?: string;
    tinNumber?: string;
    roundAmount?: number;
    standrdInvnTxReportLines?: Array<StandardInventoryTxReportLine>;
}
