/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IStitchingVendor } from './iStitchingVendor';


export interface StitchingItemHistoryReportLine { 
    date?: Date;
    voucherNumber?: string;
    dueDate?: Date;
    vendor?: IStitchingVendor;
    description?: string;
    quantity?: number;
    rate?: number;
    amount?: number;
    totalAmount?: number;
    status?: string;
}
