/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IStitchingItem } from './iStitchingItem';
import { IStitchingVendor } from './iStitchingVendor';


export interface StitchingVendorReportArgument { 
    dateFrom?: Date;
    dateTo?: Date;
    dueDate?: Date;
    chkDueDate?: boolean;
    vendor?: IStitchingVendor;
    stitchingItem?: IStitchingItem;
    status?: string;
}
