/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaxRateWiseSalePurchaseSummaryLine } from './taxRateWiseSalePurchaseSummaryLine';


export interface TaxRateWiseSalePurchaseSummary { 
    dateFrom?: Date;
    dateTo?: Date;
    saleReportLines?: Array<TaxRateWiseSalePurchaseSummaryLine>;
    purchaseReportLines?: Array<TaxRateWiseSalePurchaseSummaryLine>;
}
