/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ILedger } from './iLedger';
import { TDSCommissionReportLine } from './tDSCommissionReportLine';


export interface TDSCommission { 
    ledger?: ILedger;
    tdsRate?: number;
    dateFrom?: Date;
    dateTo?: Date;
    totalAmount?: number;
    totalCommission?: number;
    totalTds?: number;
    reportLine?: Array<TDSCommissionReportLine>;
}
