/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TrialBalanceLedgerReportLine } from './trialBalanceLedgerReportLine';


export interface TrialBalanceLedgerGroupReportLine { 
    ledgerGroup?: string;
    debit?: number;
    credit?: number;
    reportLedgerLines?: Array<TrialBalanceLedgerReportLine>;
    ledgerGroupBalance?: number;
}
