/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Vat18 } from './vat18';
import { Vat19 } from './vat19';
import { Vat23 } from './vat23';
import { Vat24 } from './vat24';


export interface Vat15 { 
    name?: string;
    tin?: string;
    address?: string;
    pin?: string;
    telephone?: string;
    fax?: string;
    email?: string;
    pan?: string;
    quarter?: string;
    financialYear?: string;
    vat23?: Vat23;
    vat24?: Vat24;
    vat18?: Vat18;
    vat19?: Vat19;
}
