/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Vat24Entry } from './vat24Entry';
import { Vat24SummaryEntry } from './vat24SummaryEntry';


export interface Vat24 { 
    entries?: Array<Vat24Entry>;
    summaryEntries?: Array<Vat24SummaryEntry>;
}
