/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Vat23Entry } from './vat23Entry';
import { Vat23SummaryEntry } from './vat23SummaryEntry';


export interface Vat23 { 
    entries?: Array<Vat23Entry>;
    summaryEntries?: Array<Vat23SummaryEntry>;
}
